// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var apiEndpoint = "http://immense-river-25513.herokuapp.com/locations";

function decodeLocaton(json) {
  return /* record */[
          /* username */Json_decode.field("username", Json_decode.string, json),
          /* location */Json_decode.field("location", (function (param) {
                  return Json_decode.pair(Json_decode.$$float, Json_decode.$$float, param);
                }), json)
        ];
}

function getData() {
  return fetch(apiEndpoint).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(Json_decode.array(decodeLocaton, json));
              }));
}

exports.apiEndpoint = apiEndpoint;
exports.decodeLocaton = decodeLocaton;
exports.getData = getData;
/* No side effect */
