// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Api$ReactTemplate = require("./Api.bs.js");
var Map$ReactTemplate = require("./Map.bs.js");

var component = ReasonReact.reducerComponent("App");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              Api$ReactTemplate.getData(/* () */0).then((function (data) {
                      Curry._1(self[/* send */3], /* Fetch */[data]);
                      return Promise.resolve(data);
                    }));
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Map$ReactTemplate.ComposableMap[/* make */0](800, 600, /* array */[ReasonReact.element(/* None */0, /* None */0, Map$ReactTemplate.ZoomableGroup[/* make */0](/* array */[
                                            ReasonReact.element(/* None */0, /* None */0, Map$ReactTemplate.Geographies[/* make */0]("../world.json", (function (geographies, projection) {
                                                        return $$Array.map((function (geography) {
                                                                      return ReasonReact.element(/* Some */[geography.id], /* None */0, Map$ReactTemplate.Geography[/* make */0](geography, projection, /* array */[]));
                                                                    }), geographies);
                                                      }))),
                                            ReasonReact.element(/* None */0, /* None */0, Map$ReactTemplate.Markers[/* make */0](/* array */[$$Array.map((function (marker) {
                                                              return ReasonReact.element(/* Some */[marker[/* username */0]], /* None */0, Map$ReactTemplate.Marker[/* make */0]({
                                                                              coordinates: marker[/* location */1]
                                                                            }, /* array */[React.createElement("circle", {
                                                                                    cx: "0",
                                                                                    cy: "0",
                                                                                    fill: "red",
                                                                                    r: "6"
                                                                                  })]));
                                                            }), self[/* state */1][/* dojos */0])]))
                                          ]))])));
            }),
          /* initialState */(function () {
              return /* record */[/* dojos : array */[]];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              return /* Update */Block.__(0, [/* record */[/* dojos */action[0]]]);
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
